export const KEYS = {
  BASE_URL: import.meta.env.VITE_BASE_URL,
  WEB_SOCKET_URL: import.meta.env.VITE_WEB_SOCKET_URL,
  ACCESS_TOKEN_KEY: import.meta.env.VITE_ACCESS_TOKEN_KEY,
  REFRESH_TOKEN_KEY: import.meta.env.VITE_REFRESH_TOKEN_KEY,
  GOOGLE_PLACE_API_KEY: import.meta.env.VITE_GOOGLE_PLACE_API_KEY,
  PUBLIC_S3_PREFIX: import.meta.env.VITE_PUBLIC_S3_PREFIX,
  ROUND_TO_NEAREST: import.meta.env.VITE_ROUND_TO_NEAREST,
  MAX_RESTAURANT_IMAGES: import.meta.env.VITE_MAX_RESTAURANT_IMAGES,
  MAX_RESTAURANT_IMAGE_SIZE_IN_MB: import.meta.env
    .VITE_MAX_RESTAURANT_IMAGE_SIZE_IN_MB,
  FIREBASE_VAPID_KEY: import.meta.env.VITE_FIREBASE_VAPID_KEY,
  CLIENT_WEBSITE_URL: import.meta.env.VITE_CLIENT_WEBSITE_URL,
} as const;
